BANCO DE DADOS - CARROS

LETRA A:

CREATE DATABASE carros;
USE  carros;

CREATE TABLE marca (
	codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(30) NOT NULL,
	pais VARCHAR(30) NOT NULL
);

CREATE TABLE modelo (
	codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(30) NOT NULL,
	categoria VARCHAR(30) NOT NULL,
	cor VARCHAR(30) NOT NULL,
	codigo_marca INT NOT NULL,
	CONSTRAINT FK_marca	FOREIGN KEY (codigo_marca) REFERENCES marca (codigo)
);